#!/bin/sh /etc/rc.common
#
# SPDX-License-Identifier: Apache-2.0
#
# luci-app-ddm init script
#
# 通过 UCI (/etc/config/ddm) 控制后台 DDM 告警守护进程：
#
#   config ddm 'main'
#       option enabled '1'
#       option interval '60'
#       option log_changes_only '1'

START=95
STOP=10

USE_PROCD=1
PROG=/usr/libexec/ddm/ddm-daemon.sh

start_service() {
	local enabled interval changes

	config_load ddm
	config_get_bool enabled main enabled 0
	config_get interval main interval 60
	config_get_bool changes main log_changes_only 1

	[ "$enabled" -eq 1 ] || return 0
	[ -x "$PROG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG" "$interval" "$changes"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	rm -f /var/run/ddm.state
}
